src/pages/posts/js/reactjs-et-rendu-serverside/index.jade, src/pages/posts/js/reactjs-et-rendu-serverside/index.md
relecture poke @putaindecode/owners
=> post - react et le rendu coté serveur

src/partials/footer.jade
=> Fixed: footer.jade trigger "Element a not allowed as child of element ul in this context

src/pages/posts/env/vim/il-demarre-vim-par-erreur-ce-qui-se-passe-ensuite-est-tout-simplement-bluffant/index.md
- toujours utilisé aujourd'hui (entre autres) car on peut l'utiliser  --> je ne vois pas l'intérêt de (entre autres), j'ai dû relire plusieurs fois pour comprendre ce que tu voulais dire
- un couple d'heures --> un peu trop anglicisme pour moi
=> Fix typos in post about Vim introduction

src/pages/posts/css/du-css-evolutif/index.jade, src/pages/posts/css/du-css-evolutif/index.md
Un petit article sur du CSS poke @putaindecode/owners
=> Du CSS Evolutif

src/authors/awillemant.json, src/pages/posts/api/hateoas/index.jade, src/pages/posts/api/hateoas/index.md, tasks/cache/contributors.cache
Deuxième version avec vos retours
Un article "un peu moins insolent" que le premier jet je l'espère
Merci encore, à votre dispo
=> article HATEOAS

src/pages/posts/api/hateoas/index.md
Petite inversion dans le dernier article.
=> Fix: HATEOAS, le Graal des développeurs d'API

src/pages/posts/api/hateoas/index.md
Reverts putaindecode/putaindecode.fr#354
=> Revert "Fix: HATEOAS, le Graal des développeurs d'API"

content/posts/js/implementer-flux/index.md
=> add post on implementing flux

content/posts/js/utiliser-react-en-moteur-de-templates/index.md
=> [Post] Utiliser React en moteur de templates

content/posts/js/utiliser-react-en-moteur-de-templates/index.md
=> A few typos and common grammar mistakes

package.json
This is now correctly provided by cssnext
Closes #405
=> Remove caniuse-api hard dependency.

content/posts/entreprendre/auto-entrepreneuriat-retour-experiences/index.md, content/posts/windows/comment-coder-sous-windows/index.md, src/modules/Post/index.jsx
=> Handle hero images as post metadata

content/authors/Erwyn.json, content/authors/Macxim.json, content/authors/OwlyCode.json, content/authors/awillemant.json, content/authors/bloodyowl.json, content/authors/bmeurant.json, content/authors/justinmarsan.json, content/authors/magsout.json, content/authors/neemzy.json, content/authors/syvuilliot.json
Documentation is still to be written.
=> Quick fixes in authors' bio (third person). That should fix #353 

content/index.md
Because it as to be done in some fashion.
=> Update the introduction on the homepage

content/posts/css/introduction-a-cssnext/index.md, content/posts/css/petite-definition-bem/index.md
- Transpileur: http://fr.wikipedia.org/wiki/Compilateur_source_%C3%A0_source
- j'ai viré le détail sur mixins, extend et nesting, car les 2 derniers arrivent dans css, je préfère éviter le reverse troll ^^
- j'ai rajouté une note sur l'option `browsers`
- j'ai fait pointé le lien BEM vers chez nous, j'y ajouterais ton lien en bas de l'article
- petite mention de babeljs
=> Post: introduction à cssnext, some changes

src/css/blocks/navigation.css
=> Fix putainde-Nav-item

CONTRIBUTING.md
=> Add note for bio at the third person

CONTRIBUTING.md
=> Add max width to image in CONTRIBUTING.md

CONTRIBUTING.md
Entre l'infinitif (en mode recette) et le tutoiement/vouvoiement, il y en a pour tous les goûts.
Désormais on utilise l'impératif pour les actions à effectuer et le tutoiement pour les conseils et how-to.
=> Fix: mise en conformité du tutoiement/vouvoiement

content/posts/env/semver-c-est-quoi/index.md
=> Post: semver, use a gradient to make readability easier

accounts.json
This twitter account is dead (like backbone for most of us), so I guess we should just remove this from this file.
I guess we should do something with this account ? poke @kud
=> Remove outdated backbone twitter account

content/posts/js/introduction-gulp/index.md
Ref http://putaindecode.fr/posts/js/introduction-gulp/#comment-2108371825
J'ai pris le hash du dernier commit où y'avait encore gulp et j'ai modifié un poil les phrases pour l'indiquer.
Au passage, un peu de propagrande cssnext.
=> Post: Gulp, update to fix outdated stuff

content/posts/js/premiers-pas-avec-grunt/index.md, src/css/blocks/note.css, src/index.css
J'en avais parlé, vous en pensez quoi ?
Dans l'idée je ferais de même sur l'article de Gulp vers Webpack.
Je n'ai pas fait volontairement grunt->webpack pour éviter la violence. Une évolution à la fois imo.
=> Post: grunt, add note about gulp which is better in many way

content/posts/webpack/index.md
@MoOx j'ai tenté de faire un peu plus générique au début
=> Corrections et réorganisation

content/posts/webpack/index.md
2 commits pour parfaire cette courte introduction à webpack :
1. correction d'orthographe
2. correction d'anglicisme
Ça vous convient ?
=> Fix.webpack

content/authors/revolunet.json, content/posts/github-pages/introduction/index.md
quelques corrections, sorry
ATOM a supprimé les espaces en fin de ligne...
=> replace googlemaps instructions with leaflet, and update profile

content/en/posts/js/introduction-to-reactjs/index.en.md, content/posts/js/utiliser-react-en-moteur-de-templates/index.md
Okay, I tried to do this quickly just to give a taste of what it could look like.
This is in no way final or anything, just a quick preview.
I tried to keep @bloodyowl's writing style while not making it too literal a translation (which was kinda easy; boy how many anglicisms do you use?)
=> [translation] Post: Introduction à React

content/en/posts/html/responsive-dom/index.md
Comme promis il y a un moment maintenant, voici la traduction en anglais de mon premier article sur P! Le second suivra quand j'aurais un moment (encore).
Bisous
=> Post: Responsive webdesign and DOM structure (english translation)

package.json, scripts/build.js
=> Added svgo-loader for cleaning SVG

content/en/articles/js/react/unit-testing.md, content/fr/articles/js/react/test-unitaires.md
Note: I will review it, I was wrote it 2 weeks ago and didn't (yet) reviewed it myself. This PR is a reminder :)
You can still review and give your thoughts.
I will translate it into french probably tomorrow.
=> Post: Unit testing React components

content/fr/articles/js/react/test-unitaires.md
=> Fix: test-unitaires.md

content/authors/leoderbois.json, content/fr/articles/xcode/storyboards/avantages-a-diviser-ses-storyboards/index.md
- new branch à partir de master (plus propre/simple)
- H3 au lieu de la liste
- 80 chars max
- changement de la date au 01/12/05
- dossier : xcode/storyboards
note : suite de
https://github.com/putaindecode/putaindecode.io/pull/543
=> Post : Avantages à diviser ses storyboards en iOS/OS X

content/fr/articles/js/es2015/const-let-var.md
ok guise, let's review this please!
=> [Post] ES6 variables: let/const

content/en/articles/js/es2015/const-let-var.md, content/fr/articles/js/es2015/const-let-var.md
Translation of @Nyalab post.
Feel free to merge asap so we can release it today.
=> Post: ES6, ES2015 : declaring variables using const, let and var

content/en/articles/js/es2015/defaults.md, content/en/articles/js/es2015/destructuring.md, content/en/events/2015/advent-calendar/index.md, content/fr/articles/js/es2015/defaults.md, content/fr/articles/js/es2015/destructuring.md, content/fr/evenements/2015/calendrier-avent/index.md
Feel free to push fixes after this PR ;)
=> Add translation for ES6 destructuring and defaults

content/en/articles/js/es2015/object-assign.md, content/en/events/2015/advent-calendar/index.md, content/fr/evenements/2015/calendrier-avent/index.md
Should following #558 
@naholyr I used `const` in the translation while I am waiting for comments :)
=> Post: ES6/2015 Object.assign - translation in english + add in calendars

content/fr/articles/js/es2015/template-strings.md
Needs some adjustements and review
=> Post : ES6 template strings

content/en/articles/js/es2015/classes.md, content/en/events/2015/advent-calendar/index.md, content/fr/articles/js/es2015/classes.md
Merging, but feel free to review and push fixes.
=> Translation: post on es6 classes

content/fr/articles/js/es2015/object-literals.md
Hello,
voici le post sur les object literal, hésitez pas à faire les corrections si y'a besoin de le sortir rapidement, car vu que je suis a dotjs, je pourrais pas trop faire les modif rapidement meme si je vais essayer de suivre les retours.
=> Post es6: object literal

content/en/articles/js/es2015/promises.md, content/en/events/2015/advent-calendar/index.md, content/fr/articles/js/es2015/promises.md
Merging because of the delay, feel free to review.
=> Post translation: es6 promises

content/en/articles/js/es2015/template-strings.md, content/en/events/2015/advent-calendar/index.md, content/fr/articles/js/es2015/template-strings.md
Merging since we are late, but feel free to review.
(poke @jbleuzen)
=> Post translation: es6 template strings

content/en/articles/js/es2015/object-literals.md, content/en/events/2015/advent-calendar/index.md
=> Post translation: es6 object literals

content/fr/articles/js/es2015/promises.md
https://github.com/putaindecode/putaindecode.io/pull/586
=> Fix post: replace promises by promesses

content/en/articles/js/es2015/iterators.md, content/en/events/2015/advent-calendar/index.md, content/fr/articles/js/es2015/iterators.md
This also includes some minors adjustments in the code of the original
post (poke @ ffesseler)
=> Post translation: ES6 iterators

content/authors/zoontek.json, content/fr/articles/js/es2015/rest-spread.md
Désolé pour le retard, grosse semaine!
=> Post: rest & spread

content/authors/zoontek.json, content/en/articles/js/es2015/iterators.md, content/en/events/2015/advent-calendar/index.md, content/fr/articles/js/es2015/iterators.md, content/fr/articles/js/es2015/maps-weakmaps.md, content/fr/articles/js/es2015/rest-spread.md, content/fr/evenements/2015/calendrier-avent/index.md
Remplacement de callback par callbacks la ou c’était utile
=> Fix Post: Example d'utilisation des WeakMap

content/en/articles/js/es2015/arrow-functions.md, content/en/events/2015/advent-calendar/index.md, content/fr/articles/js/es2015/arrow-functions.md, content/fr/evenements/2015/calendrier-avent/index.md
Fr + en, probably with lots of spelling mistakes...
Tell me if the global structure is ok.
=> Post ES6 arrow functions (fr/en)

.gitignore, content/en/articles/js/es2015/for-of.md, content/fr/articles/js/es2015/for-of.md
French article about ES6 `for..of` loop to review, I'll translate it to english once it's approved.
=> Post ES6 for..of (fr/en)

content/authors/clementd.json, content/fr/articles/js/es2015/symbols.md
Uniquement en français pour le moment (ça pose problème si la traduction en arrive après ?)
=> Post: ES2015 symbols

content/authors/DavidBruant.json, content/fr/articles/js/es2015/proxy.md
It's a first draft open for review.
I haven't looked at styling conventions yet.
I'm happy to make any change you'd deem necessary.
The article is a bit long at times, but the topic is itself hairy. As I suggested in my comment in #553, maybe this article covers the Reflect API enough (it's hard to distangle both topics as explained in the post)
=> Post: es6 proxies

content/en/articles/js/es2015/symbols.md
Not sure about the date, I've kept the one from the original post (in French)
=> Post ES2015: Symbols (english translation)

content/authors/freezystem.json
Juste l'ajout de ma bio dans authors
=> Bio: Freezystem - write my bio

content/fr/articles/js/es2015/classes.md
According to MDN:
> The bodies of class declarations and class expressions are executed in strict mode.
=> Strict mode clarification

content/en/articles/js/es2015/arrow-functions.md, content/fr/articles/js/es2015/arrow-functions.md
Actually the modified snippet is perfectly valid JS.
=> Correct arrow function misunderstanding

web_modules/Author/index.js, web_modules/AuthorsList/index.js, web_modules/Avatar/index.js, web_modules/Avatars/index.js, web_modules/Contributor/index.js, web_modules/Contributors/index.js, web_modules/Footer/index.js, web_modules/GoogleAnalyticsTracker/index.js, web_modules/Header/index.js, web_modules/Html/index.js, web_modules/LatestPosts/index.js, web_modules/Layout/AdventCalendar/index.js, web_modules/Layout/Page/index.js, web_modules/Layout/PageError/index.js, web_modules/Layout/Post/index.js, web_modules/Layout/Posts/index.js, web_modules/Layout/WithHeroHeader/index.js, web_modules/Layout/index.js, web_modules/Navigation/index.js, web_modules/Page/index.js, web_modules/PostPreview/index.js, web_modules/PostsList/index.js, web_modules/ReadingTime/index.js, web_modules/SVGIcon/__tests__/index.js, web_modules/TopContributors/index.js
we also get the reading time back
=> [Website] Remove unnecessary 'extends Component' ~ fixes #510

content/en/articles/php/injection-dependances/index.md
=> Post: Dependency injection with PHP (english translation)

content/authors/thib_thib.json, content/en/articles/css/tooling-evolution/index.md, content/fr/articles/css/tooling-evolution/index.md
Following this issue : https://github.com/putaindecode/putaindecode.io/issues/616
I'll translate the article in french as soon as possible !
=> Post: CSS tooling evolution

content/fr/articles/js/es2015/arrow-functions.md, web_modules/Contributor/index.js, web_modules/Contributors/index.js, web_modules/Layout/Post/index.js
=> [website] add reviewers management ~ fixes #486

web_modules/_legacy-css/blocks/author.css
=> Fix rounded borders on author block

content/fr/articles/swift/hello/index.md
Mise à jour Swift 2.2 pour les ++/-- et adaptations des exemples pour les boucles.
=> Fix : Hello Swift : mise à jour pour Swift 2.2/3

package.json, scripts/build.js, scripts/config.js, scripts/index-client.js, scripts/webpack.config.babel.js, scripts/webpack.config.client.js, web_modules/app/routes.js, web_modules/app/store.js, web_modules/layouts/Homepage/index.js, web_modules/layouts/PageLoading/index.js, web_modules/layouts/PageLoading/styles.css, web_modules/layouts/Posts/index.js, web_modules/layouts/index.js
No big change under the hood for now.
Bonus, PageLoading has been added (from default boilerplate), which
closes #500.
For a preview of the loading state, see https://phenomic.io/loading/ (I just adapted the color of the spinner).
=> Upgrade statinamic (now phenomic) to 0.10.0

content/fr/articles/js/angular/components/index.md
Que pensez vous de suivre les guides de style angular ? 
https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y032
https://github.com/toddmotto/angular-styleguide
https://github.com/mgechev/angularjs-style-guide#controllers
Dans ces 3 guides, il est recommandé d'utiliser une variable dans les `controllers` pour capturer la variable `this` quand on utilise `controllerAs`. Ce qui permet également d'éviter l'utilisation de `angular.bind`
=> guide de style Angular vm vs angular.bind

content/fr/articles/ci/travis-ci/index.md
Pour continuer #332.
Si ça vous plait, que c'est clair toussa, je ferais la version EN avant publication.
=> Post: Déploiement continu avec Travis-CI (et GitHub Pages)

content/fr/articles/js/webpack/index.md
=> [FR] Fix typo in Webpack post

content/fr/articles/ci/travis-ci/index.md
J'ai voulu corriger « vous aller » seulement mais j'ai profité de cette proposition pour appliquer quelques règles du français et corriger un commentaire dans un code d'exemple.
=> Fix : Déploiement continu avec Travis-CI

content/en/articles/js/flow/index.md
=> English translation for Flow introduction

content/fr/articles/js/es2015/array-methods-addition.md
=> Fix typo: querySeletorAll en querySelectorAll

content/fr/articles/js/react/native/introduction/index.md
Android takes a capital letter at the start, dangnabbit!
=> Grammar and styling changes in ReactNativeIntro

content/fr/articles/css/centrer/index.md
Just fix a small comment from "height" to "width"
=> Fix comment

content/fr/articles/podcast/1/index.md
rien de bien méchant :
- un auxiliaire oublié
- un tiret de trop
- un tiret oublié
=> Quelques typos

src/layouts/Homepage/index.js, src/layouts/Homepage/styles.css
Require #706 to work properly.
=> Add banner for postcast on homepage (french only)

content/fr/articles/js/react/styled-components/index.md
=> Post styled components

content/fr/articles/js/prettier/index.md
Juste une petite coquille sur une lettre ("vous m'utilisez" en "vous n'utilisez")
=> Post/prettier - Correction

content/fr/articles/podcast/1/index.md, content/fr/articles/podcast/2/index.md, content/fr/articles/podcast/3/index.md, content/fr/articles/podcast/4/index.md
poke @bloodyowl 
A merger après #720
=> [post] Adjust some meta on podcasts

content/fr/articles/js/react/styled-components/index.md
Bonsoir,
J'ai remarqué une petite faute de frappe sur le très bon post "Introduction à styled-components". Voici donc la correction :)
=> Fix typo sur l'article styled-components

content/fr/articles/swift/hello/index.md
Petite update des exemples pour Swift  4.
=> mise à jour pour Swift 4

content/fr/articles/tdd/index.md
Bon article d'introduction au TDD, BDD 👏 
> Le TDD est une pratique controversée car coûteuse à mettre en place.
Cela dépend vraiment du contexte, sur un projet avec des développeurs expérimentés en TDD le coût d'ajout de nouvelles fonctionnalités sera bien moindre.
Sur une grosse base de code non testée forcément c'est coûteux et cela demande un refactoring au fil de l'eau, mais l'ajout de fonctionnalité est lui aussi bien plus coûteux.
Exemple dans cet article sur la dette technique : https://frank.taillandier.me/2014/11/06/intro-dette-technique/#ce-que-repr%C3%A9sente-exactement-la-dette-technique
=> Corrections

content/authors/drazik.json, content/fr/articles/semver/semantic-release/index.md
add drazik bio json
80 chars max
typos and improvements
add precision
=> first draft

content/fr/articles/js/flow/advanced-part-1.md
(Désolé pour le naming des variables)
=> Flow advanced: Part 1 post

content/fr/articles/npm/install-g/index.md
=> [post] stop aux npm install -g sauvages

content/fr/articles/npm/install-g/index.md
=> correction coquilles

content/authors/leolelego.json, content/fr/articles/swift/closure/index.md, content/fr/articles/swift/hello/index.md, content/fr/articles/xcode/storyboards/diviser/index.md
avoir son propre nom c'est bien trop sérieux. Avant, jeune développeur, je croyais que je devais être sérieux! (et j'aime pas trop cette image de moi ^^)
j'ai changé le fichier authors et tous (c'est un grand mot) les articles.
=> Change ressources for renaming user leoderbois to leolelego

content/fr/articles/js/react/react-new-context-api/index.md
=> Fixed typos in React Context API post

content/fr/articles/git/synchroniser-sans-effort-ses-depots-git-entre-github-gitlab-bitbucket.md
J'avais ça en draft depuis un moment...
=> Garder ses dépôts Git synchronisés sur GitHub, GitLab & Bitbucket

content/fr/articles/js/react/react-hooks/index.md
=> add React Hooks post

content/authors/neemzy.json
=> Updated neemzy's bio

articles/2019-03-21-une-ui-responsive-grace-a-la-regle-de-trois.md
Je sais pas trop si l'intention de l'auteur était « nous prenons » ou « en prenant » :)
=> Fix typo in ui responsive post

articles/2014-06-13-un-point-sur-les-grilles-css-en-inline-block.md
See https://putaindecode.io/articles/un-point-sur-les-grilles-css-en-inline-block/
=> Missing space for Markdown

.prettierignore, bsconfig.json, package.json, yarn.lock
=> add prettier so people can use it in their IDE if they want

articles/2020-03-27-peut-on-securiser-une-application-frontend.md
Bonjour,
je viens de lire le dernier post de Putaindecode, très intéressant. Et j'ai trouvé quelques typos en passant, donc je propose quelques corrections
=> Typo fixes

src/pages/Article.re, src/pages/PodcastEpisode.re
=> Design fixups

src/shared/Header.res
- Kind of outdated ?
- Should be Urkaine ?
- Maybe our website should do this kind of banner ?
=> Remove banner
